name: npm test
on:
  workflow_dispatch:

#jobs:
#  npm-install:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 14
#      - run: npm ci
#      - run: npm run test

jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/ex5.yaml
        with:
          node-version: '14'

