name: interact with Github API
on:
  pull_request:

jobs:
  trigger-issue-creation:
    runs-on: ubuntu-latest
    steps:
      - name: createIssue
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/gabbloquet/github-actions-sandbox/issues \
            -d '{"title":"Hey, I'm a Github Actions !","body":"Well done !","assignees":["octocat"],"milestone":1,"labels":["bug"]}'