name: reusable workflow
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: node version
        required: false
        type: string

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name : setup node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ inputs.node-version }}'
      - name: run test
        shell: bash
        run: |
          node -v
          npm install
          npm test