name: npm test docker
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name : setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: run install
        shell: bash
        run: |
          npm install
          npm test
      - name: docker push
        if: github.ref_name == 'main' && github.event_name == 'push'
        run : |
          echo ${{ github.ref }}
          docker build -t ${{ github.sha }} .