name: npm test matrix
on:
  workflow_dispatch:

jobs:
  run-npm-install_matrix:
    strategy:
      max-parallel: 6
      matrix:
        version: [12, 14, lts/*]
        os: [ubuntu-latest, ubuntu-18.04]
    if: ( ${{ matrix.version }} == 12 && ${{ matrix.os }} == ubuntu-latest ) || ${{ matrix.version }} == 14 || ${{ matrix.version }} == lts/*
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name : setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}
      - name: run install
        shell: bash
        run: |
          npm install
          npm test